################################################################
# dev 
################################################################
version: '3'
services:
  node-app:
    build: 
      context: .  # its a location of docker file 
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev