#this is for shared configuraiton in both dev and prod environment
version: "3"
services:
  node-app:
    ports:
      - "3000:3100"
    environment:
      - PORT=3100
################################################################
# you commands would be
################################################################

#------------------------------- for the dev mode --------------------
# docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build
#docker-compose -f docker-compose.yml -f docker-compose.dev.yml down -v

#------------------------------- for the prod mode --------------------
# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up --build
#docker-compose -f docker-compose.yml -f docker-compose.prod.yml down -v
